# 数据集配置
data:
  dataset_name: "Constructed_Emotion_Dataset"
  root_dir: "Constructed_Emotion_Dataset"
  image_size: 112
  batch_size: 64
  num_workers: 16


# 模型配置
model:
  name: "face_network"
  num_classes: 6  
  dropout_rate: 0.2"
  model_checkpoints: ""  # 预训练模型路径，为空时不加载，不为空时加载指定路径的模型

# 训练配置
train:
  epochs: 100
  learning_rate: 0.001 # 学习率
  weight_decay: 0.0001 # 权重衰减因子
  optimizer: "SGD" # "AdamW""Adam""SGD"
  scheduler: "none" # 学习率调度器. "cosine"或"step"或"reduce_on_plateau"或"none"
  warmup_epochs: 5 # 预热轮数
  device: "cuda"  # "cuda"或"cpu"

# 其他配置
paths:


# 推理配置
inference:


# Matplotlib配置
matplotlib:
  backend: "Agg"
  figure_dpi: 150
  savefig_dpi: 300
  text_antialiased: true
  path_snap: false
  image_interpolation: "bilinear"
  font:
    sans_serif: ["AR PL UMing CN"]
    size: 14
    axes_titlesize: 20
    axes_labelsize: 16
    xtick_labelsize: 14
    ytick_labelsize: 14
    legend_fontsize: 14
  axes_unicode_minus: false